# Generated by Django 2.2.3 on 2020-01-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_tiny", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variable",
            options={
                "verbose_name": "Вариант",
                "verbose_name_plural": "Варианты",
            },
        ),
    ]
